# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Build"

on:
  pull_request:
  push:
    branches:
      - "master"

env:
  COMPOSER_ROOT_VERSION: "0.12.x-dev"

jobs:
  tests:
    name: "Tests"
    runs-on: ${{ matrix.operating-system }}
    continue-on-error: ${{ matrix.php-version == '8.0' }}

    strategy:
      fail-fast: false
      matrix:
        composer_version: ['v1', 'v2', 'snapshot']
        php-version:
          - "8.0"
        operating-system: [ubuntu-latest, windows-latest]
        script:
          - "vendor/bin/phing tests"
          - "vendor/bin/phing tests-fast-static-reflection"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"
          tools: pecl, composer:${{ matrix.composer_version }}
          extensions: ds,mbstring
          ini-values: memory_limit=512M

      - name: "Install dependencies"
        run: "composer update --no-interaction --no-progress"

      - name: "Update PHPUnit"
        if: matrix.php-version == '7.4' || matrix.php-version == '8.0'
        run: "composer remove --dev brianium/paratest && composer require phpdocumentor/reflection-docblock:'5.2.0' && composer require --dev phpspec/prophecy:'^1.11.1' && composer require --dev phpunit/phpunit:'^9.3' --update-with-dependencies"

      - name: "Transform source code"
        if: matrix.php-version != '7.4' && matrix.php-version != '8.0'
        run: php bin/transform-source.php

      - name: "Tests"
        run: "${{ matrix.script }}"