name: 'Extension v2 workflow'
on:
  repository_dispatch:
  push:
  schedule:
    - cron: '15 4 * * *'
jobs:
  run:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      max-parallel: 16
      matrix:
        operating-system: [ubuntu-16.04, windows-latest, macos-latest]
        php-versions: ['5.4', '5.5', '5.6', '7.0', '7.1', '7.2', '7.3', '7.4']
    name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.operating-system }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, xdebug, pcov, intl, gd, redis, xml, soap, imagick, ast, phalcon4, msgpack, gearman
      - name: Testing PHP version
        run: php -v
      - name: Testing Extensions
        run: |
          php -m
          php -r "if(! extension_loaded('mbstring')) {throw new Exception('mbstring not found');}"
          php -r "if(! extension_loaded('Xdebug')) {throw new Exception('Xdebug not found');}"
          php -r "if(! extension_loaded('intl')) {throw new Exception('intl not found');}"
          php -r "if(! extension_loaded('gd')) {throw new Exception('gd not found');}"
          php -r "if(! extension_loaded('redis')) {throw new Exception('redis not found');}"
          php -r "if(! extension_loaded('xml')) {throw new Exception('xml not found');}"
          php -r "if(! extension_loaded('soap')) {throw new Exception('soap not found');}"
          php -r "if(phpversion()>=5.5 && ! extension_loaded('imagick')) {throw new Exception('imagick not found');}"
          php -r "if(phpversion()>=7.0 && ! extension_loaded('ast')) {throw new Exception('ast not found');}"
          php -r "if(phpversion()>=7.1 && ! extension_loaded('pcov')) {throw new Exception('PCOV not found');}"
          php -r "if(phpversion()>=7.2 && ! extension_loaded('psr')) {throw new Exception('psr not found');}"
          php -r "if(phpversion()>=7.2 && ! extension_loaded('phalcon')) {throw new Exception('phalcon not found');}"
          php -r "if(phpversion()>=7.2 && phpversion('phalcon')[0]!='4') {throw new Exception('Wrong phalcon version Installed');}"
          php -r "if(phpversion()>=7.0 && ! extension_loaded('msgpack')) {throw new Exception('msgpack not found');}"
      - name: Testing gearman
        if: matrix.operating-system == 'ubuntu-latest'
        run: |
          php -r "if(phpversion()>=5.6 && ! extension_loaded('gearman')) {throw new Exception('gearman not found');}"
