name: Test
on:
  push:
  pull_request:

jobs:
  run:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-20.04]
        php: [7.4, 8.0]
    steps:
      - name: Install Kafka
        run: sudo apt-get install -y librdkafka-dev    
      - name: Setup PHP
        uses: shivammathur/setup-php@2.10.0
        with:
            php-version: ${{ matrix.php }}
            tools: cs2pr
            extensions: mbstring,bcmath,intl,gd,zip,memcached-3.1.5,redis-5.3.3,rdkafka-5.0.0
        env:
            fail-fast: true
      - run : |
          php -r "echo phpversion('memcached');"
          echo ''
          php -i | grep 'libmemcached version'
          echo ''
          php -v
          php -m
